# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidossinreceta',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
