# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20170822_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosconreceta',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='pedidossinreceta',
            old_name='id_cliente',
            new_name='cliente',
        ),
    ]
