# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(110), django.core.validators.MinValueValidator(0)]),
        ),
    ]
