# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170817_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.URLField(blank=None, default='', null=None),
            preserve_default=False,
        ),
    ]
