# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20170823_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoenstock',
            name='id_pedido_sin_receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_en_stock', to='pedidos.PedidosSinReceta'),
        ),
    ]
